name: aes
description: advanced encryption standart app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shimmer: ^2.0.0
  firebase_core: ^2.24.2
  firebase_auth: ^4.0.0
  cloud_firestore: ^4.14.0
  qr_code_scanner: ^1.0.0
  encrypt: ^5.0.3
  flutter_sound: ^9.2.13
  permission_handler: ^10.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: FontRegular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
    - family: FontBold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
    - family: FontMedium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
    - family: FontMediumItalic
      fonts:
        - asset: assets/fonts/Montserrat-MediumItalic.ttf
    - family: FontLight
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
